POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "role": "admin",
    "email": "john@doe.com"
}

###

POST http://localhost:3000/viewer HTTP/1.1
content-type: application/json

{
    "user_id": "5bbc37585e0d0e4d1e51adcf",
    "favourite_lives": ["5bbc37585e0d0e4d1e52adcf"]
}

###

PUT http://localhost:3000/viewer/5bbc3f6ed86a8c508b5f1f91 HTTP/1.1
content-type: application/json

{
    "favourite_lives": ["5bbc37585e0d0e4d1e52adcf", "5bbc37585e0d0e4d1e53adcf"]
}


###

GET http://localhost:3000/streammer HTTP/1.1

###

GET http://localhost:3000/viewer/5bbc3f6ed86a8c508b5f1f91 HTTP/1.1

###

DELETE http://localhost:3000/viewer/5bbc3f6ed86a8c508b5f1f91 HTTP/1.1